ReaderBook/ReaderBook/Controllers/LivrariaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ReaderBook.Controllers
{
    public class LivrariaController : Controller
    {
        // GET: Livraria
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult QuemSomos()
        {
            return View();
        }
        public ActionResult Inserir()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Inserir(Models.ModelLivros livros)
        {
            Business.LivroBusiness business = new Business.LivroBusiness();
            business.Inserir(livros);

            return View();
        }
        public ActionResult Listar()
        {
            Business.LivroBusiness business = new Business.LivroBusiness();
            List<Models.ModelLivros> lista = business.Listar();

            return View(lista);
        }
        public ActionResult InserirVendas()
        {
            return View();
        }
        [HttpPost]
        public ActionResult InserirVendas(Models.ModelVendas venda)
        {
            Business.LivroBusiness business = new Business.LivroBusiness();
            business.InserirVendas(venda);

            return View();
        }
        public ActionResult ListarVendas()
        {
            Business.LivroBusiness business = new Business.LivroBusiness();
            List<Models.ModelVendasRelacional> lista = business.ListarVendas();

            return View(lista);
        }

        public ActionResult Alterar(int id)
        {
            Business.LivroBusiness business = new Business.LivroBusiness();
            Models.ModelLivros livros = business.Filtrar(id);

            return View(livros);
        }
        [HttpPost]
        public ActionResult Alterar(Models.ModelLivros l)
        {
            Business.LivroBusiness business = new Business.LivroBusiness();
            business.Alterar(l);

            return RedirectToAction("Listar");
        }


        public ActionResult Deletar(int id)
        {
            Business.LivroBusiness business = new Business.LivroBusiness();
            Models.ModelLivros livros = business.Filtrar(id);

            return View();
        }
        [HttpPost]
        public ActionResult Deletar(int id,Models.ModelLivros l)
        {
            Business.LivroBusiness business = new Business.LivroBusiness();
            business.Deletar(id);

            return RedirectToAction("Listar");
        }
    }
}

ReaderBook/ReaderBook/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Reader Book", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Inicio", "Index", "Livraria")</li>
                    <li>@Html.ActionLink("Quem somos", "QuemSomos", "Livraria")</li>

                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>